### ISSUE TITLE
Live version returns a 403 Forbidden

### ISSUE THREAD

**Issue by bdelepine** [draeger-lab/EscherConverter#31]
Hello,

Just to let you know that [the link in the README toward the live version of EscherConverter](http://139.59.18.143/) returns a 403 Forbidden error for me:

```
Forbidden

You don't have permission to access / on this server.

Possible causes of this error include:

    The request was forbidden by rules in the .htaccess file.
    The directory you requested does not have an index.html or index.php file.
    The permissions on the file or directory are incorrect.

For details about why the request was forbidden, see the Apache error log at:

/srv/users/SYSUSER/log/APPNAME/APPNAME_apache.error.log
```

Is that an expected behaviour?

**Comment by draeger** [comment]
@bdelepine thanks a lot for pointing this out! I am happy to fix it but so far I only see the target of that link, not the page where it is. Could you please state where that link is? Much appreciated!

**Comment by draeger** [comment]
Thanks a lot! Now I see what you meant. Unfortunately, my old department, the Cognitive Systems lab, retired that service. Since I do not have control over this web service myself, my only option was to remove the broken link from the README file. I am glad, you pointed this out, and apologize for the inconvenience. To use EscherConverter, please download the latest JAR file and double-click it to launch the app. Thanks!
