### ISSUE TITLE
Connections gone after conversion

### ISSUE THREAD

**Issue by anusurendra** [draeger-lab/EscherConverter#34]
I used KeggTranslator to convert a KGML file to SBML. Then am using the EscherConverter to convert it to JSON map file to put into Escher. However, when I load the converted map to Escher, the arrows and connectors (ie the reaction direction) are gone:

![escher_img](https://user-images.githubusercontent.com/5685804/51136158-d5aa7080-1809-11e9-9fac-b4ac16d8653c.png)

**Comment by draeger** [comment]
Could you please provide the KGML file and the SBML file you generated from it?

**Comment by anusurendra** [comment]
@draeger ,
Attached are the KGML and SBML files:
[hsa00630.sbml.zip](https://github.com/draeger-lab/EscherConverter/files/2756864/hsa00630.sbml.zip)
[hsa00630.xml.zip](https://github.com/draeger-lab/EscherConverter/files/2756865/hsa00630.xml.zip)

Thanks again for your help

**Comment by draeger** [comment]
Which command-line options did you use in EscherConverter for the conversion? Could you directly provide the JSON file also, please?

**Comment by anusurendra** [comment]
@draeger,

The command I am using is ```java -jar EscherConverter-1.2.0.jar --input=/home/surendraa/Downloads/hsa00630.sbml --output=/home/surendraa/Downloads/hsa00630.json --format=Escher --log-level=ALL --gui=FALSE --canvas-default-height=1E9 --canvas-default-width=1E9 --label-height=1E9 --label-width=1e9```

Attached is the converted json file:

[hsa00630.json.zip](https://github.com/draeger-lab/EscherConverter/files/2756908/hsa00630.json.zip)

**Comment by draeger** [comment]
I noticed why no arrows are added. The responsible class is [SBML2Escher](https://github.com/draeger-lab/EscherConverter/blob/master/src/main/java/edu/ucsd/sbrg/escher/converter/SBML2Escher.java), where the method [createSegments](https://github.com/draeger-lab/EscherConverter/blob/0240fde235b85188a6b071f4b5d534bd8c8105ef/src/main/java/edu/ucsd/sbrg/escher/converter/SBML2Escher.java#L515) has an `if` clause whose body only gets executed if a `listOfCurveSegments` is defined. However, the [SBML layout specification](http://co.mbine.org/specifications/sbml.level-3.version-1.layout.version-1.release-1.pdf) defines an alternative way of specifying how to connect `speciesGlyphs` and `reactionGlyphs` via the `boundingBox` of the `speciesReferenceGlyph`. KEGGtranslator does not create any curve objects so that this condition is never satisfied. However, your example SBML file also doesn't contain any bounding boxes for `speciesReferenceGlyph`s either. It seems that KEGGtranslator did not create those. At this time, I don't know why they are missing, but it is clear that EscherConverter does require Curve objects here. It would need changing the implementation to get this fixed.

**Comment by anusurendra** [comment]
@draeger ,
The SBML file was created by the KEGGtranslator, using the default preferences, to convert the KGML file to SBML. I pulled down the KGML file using ```wget http://rest.kegg.jp/get/hsa05130/kgml  2>&1 hsa00630.xml```. I tried to use KEGGtranslator to directly pull down the KGML file but I kept getting a unable to connect to Kegg error. That is why I used ```wget```. Should I have converted it to SBML_L3V1, instead of SBML?
 Thanks again for your help

**Comment by anusurendra** [comment]
@draeger ,

Attached is a picture of the conversion using KeggTranslator:
![image](https://user-images.githubusercontent.com/5685804/51188845-c3354300-18ac-11e9-9170-e16fcd122c85.png)


Here are the preferences used:
![image](https://user-images.githubusercontent.com/5685804/51188898-dd6f2100-18ac-11e9-8f69-ceeb82826f7b.png)


![image](https://user-images.githubusercontent.com/5685804/51188938-f8da2c00-18ac-11e9-9a13-a0fdc4897774.png)

**Comment by draeger** [comment]
It is recommended to check the boxes `Remove orphans` (to remove nodes that are no longer connected to any process after augmenting KEGG's information) and `Remove white gene nodes` because the purpose of creating a model from KEGG is to be specific to a target organism or tissue. White nodes are those that refer to a non-existing generic organism. But both shouldn't impact how the SBML is created.

**Comment by draeger** [comment]
In response of the question
> Should I have converted it to SBML_L3V1, instead of SBML?
Yes, because it is more specific, but it seems this is the default already.

**Comment by anusurendra** [comment]
@draeger ,
I have made the changes that you recommended and converted it ti SBML_L3V1.
However I still get the same error:
![image](https://user-images.githubusercontent.com/5685804/51190136-8ae33400-18af-11e9-9aaf-4750e505e642.png)

![image](https://user-images.githubusercontent.com/5685804/51190158-96365f80-18af-11e9-9cb8-e3b8839ad664.png)

![image](https://user-images.githubusercontent.com/5685804/51190243-cb42b200-18af-11e9-9b3c-167726414e09.png)

**Comment by draeger** [comment]
It is not surprising because the SBML is still generated in the same way. You just receive a slightly different structure. The problem you are encountering seems to be a combination of an error in KEGGtranslator that does not write out `boundingBoxe`s for `speciesReferenceGlyph`s and EscherConverter that expects even `curve` objects to be defined in the SBML files and cannot deal with the information from `speciesReferenceGlyph`s alone. However, it is not that difficult to guess from the position of nodes and the position of reaction centers where the arrows should be.

**Comment by draeger** [comment]
So, the easiest fix would be to change the interpretation of SBML in EscherConverter in method [createSegments](
https://github.com/draeger-lab/EscherConverter/blob/0240fde235b85188a6b071f4b5d534bd8c8105ef/src/main/java/edu/ucsd/sbrg/escher/converter/SBML2Escher.java#L515). There should be an `else` clause that tries to infer curve segments from `speciesReferenceGlyphs`. I will look into that, but it will take a bit time.

**Comment by anusurendra** [comment]
@draeger ,
Do I make this change in the source code and then recreate the jar file?

Thanks again.

**Comment by draeger** [comment]
It requires me to create a new release. If you can fix it yourself, I'd be happy to review your patch. That's probably faster. Otherwise, I'll do it.

**Comment by anusurendra** [comment]
@draeger ,

I am looking for that method and do not find it. Is it within escherconverter.py?

**Comment by draeger** [comment]
Here: 
https://github.com/draeger-lab/EscherConverter/blob/0240fde235b85188a6b071f4b5d534bd8c8105ef/src/main/java/edu/ucsd/sbrg/escher/converter/SBML2Escher.java#L515

**Comment by anusurendra** [comment]
@draeger ,

Thanks again. I will wait for a new version of the EscherConverter.

**Comment by draeger** [comment]
@anusurendra, if you are interested, we could add improvement of EscherConverter as a new Google Summer of Code project to https://github.com/nrnb/GoogleSummerOfCode/issues/. You would be welcome to apply for working on this funded by Google if this is appropriate. I'd be happy to guide you writing the proposal and as a mentor during the project.

**Comment by anusurendra** [comment]
Andreas,

Apologies for the delayed response. This improvement of EscherConverter as
a new Google Summer of Code project is a wonderful suggestion. I would be
very interested in this. Is this option still viable?

Anu Surendra

**Comment by draeger** [comment]
@anusurendra, Unfortunately, EscherConverter isn't part of Google Summer of Code this year. The deadline has already passed. We will need to move forward in different ways. I will try to put resources into fixing the problem. Thanks for the reminder.

**Comment by anusurendra** [comment]
Andreas,

Thanks for letting me know. Please keep me posted on any opportunities
where I can help and be part.


Anu Surendra

**Comment by MariaHei** [comment]
I'm currently trying to fix this.

**Comment by draeger** [comment]
This issue has been fixed with #37.
